"use client";

import Link from "next/link";
import { Activity, Brain, Utensils, TrendingUp, Shield, Sparkles, ChevronRight, Heart, Zap, Target } from "lucide-react";

export default function LandingPage() {
  return (
    <div style={{ minHeight: "100vh", background: "var(--bg-primary)" }}>
      {/* Nav */}
      <nav style={{
        position: "fixed", top: 0, left: 0, right: 0, zIndex: 50,
        display: "flex", alignItems: "center", justifyContent: "space-between",
        padding: "1rem 2rem",
        background: "rgba(8,12,20,0.85)", backdropFilter: "blur(16px)",
        borderBottom: "1px solid var(--border)"
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
          <div style={{
            width: 36, height: 36, borderRadius: 10,
            background: "linear-gradient(135deg,#3b82f6,#8b5cf6)",
            display: "flex", alignItems: "center", justifyContent: "center"
          }}>
            <Heart size={18} color="white" />
          </div>
          <span style={{ fontFamily: "'Space Grotesk',sans-serif", fontWeight: 700, fontSize: "1.1rem", color: "var(--text-primary)" }}>
            AI Health Planner
          </span>
        </div>
        <div style={{ display: "flex", gap: "0.75rem" }}>
          <Link href="/login">
            <button className="btn-secondary" style={{ padding: "0.5rem 1.25rem" }}>Log In</button>
          </Link>
          <Link href="/register">
            <button className="btn-primary" style={{ padding: "0.5rem 1.25rem" }}>Get Started</button>
          </Link>
        </div>
      </nav>

      {/* Hero */}
      <section style={{
        paddingTop: "10rem", paddingBottom: "6rem",
        textAlign: "center", padding: "10rem 2rem 6rem",
        position: "relative", overflow: "hidden"
      }}>
        {/* Background orbs */}
        <div style={{
          position: "absolute", top: "10%", left: "20%",
          width: 600, height: 600, borderRadius: "50%",
          background: "radial-gradient(circle, rgba(59,130,246,0.08) 0%, transparent 70%)",
          pointerEvents: "none"
        }} />
        <div style={{
          position: "absolute", top: "20%", right: "10%",
          width: 400, height: 400, borderRadius: "50%",
          background: "radial-gradient(circle, rgba(139,92,246,0.08) 0%, transparent 70%)",
          pointerEvents: "none"
        }} />

        <div className="animate-fade-in" style={{ position: "relative" }}>
          <div style={{
            display: "inline-flex", alignItems: "center", gap: "0.5rem",
            background: "rgba(59,130,246,0.1)", border: "1px solid rgba(59,130,246,0.3)",
            borderRadius: 20, padding: "0.35rem 1rem", marginBottom: "1.5rem",
            fontSize: "0.8rem", color: "#60a5fa", fontWeight: 600
          }}>
            <Sparkles size={14} /> Powered by AI
          </div>

          <h1 style={{
            fontFamily: "'Space Grotesk',sans-serif",
            fontSize: "clamp(2.5rem, 6vw, 4.5rem)",
            fontWeight: 800, lineHeight: 1.1,
            marginBottom: "1.5rem", maxWidth: 800, margin: "0 auto 1.5rem"
          }}>
            Your{" "}
            <span className="gradient-text">AI-Powered</span>
            <br />Health Journey Starts Here
          </h1>

          <p style={{
            color: "var(--text-secondary)", fontSize: "1.15rem",
            maxWidth: 600, margin: "0 auto 2.5rem", lineHeight: 1.7
          }}>
            Personalized nutrition plans, real recipes, and fitness tracking — all generated by AI based on your unique health profile and goals.
          </p>

          <div style={{ display: "flex", gap: "1rem", justifyContent: "center", flexWrap: "wrap" }}>
            <Link href="/register">
              <button className="btn-primary animate-pulse-glow" style={{ padding: "0.875rem 2rem", fontSize: "1rem" }}>
                Start Your Plan <ChevronRight size={18} />
              </button>
            </Link>
            <Link href="/login">
              <button className="btn-secondary" style={{ padding: "0.875rem 2rem", fontSize: "1rem" }}>
                I have an account
              </button>
            </Link>
          </div>
        </div>

        {/* Stats */}
        <div style={{
          display: "flex", gap: "2rem", justifyContent: "center", flexWrap: "wrap",
          marginTop: "4rem"
        }}>
          {[
            { value: "837+", label: "Real Recipes" },
            { value: "982+", label: "Ingredients" },
            { value: "73", label: "Allergy Types" },
            { value: "AI", label: "Personalized" },
          ].map((stat) => (
            <div key={stat.label} style={{ textAlign: "center" }}>
              <div style={{ fontSize: "2rem", fontWeight: 800, color: "#60a5fa", fontFamily: "'Space Grotesk',sans-serif" }}>{stat.value}</div>
              <div style={{ fontSize: "0.85rem", color: "var(--text-secondary)", marginTop: 4 }}>{stat.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Features */}
      <section style={{ padding: "4rem 2rem", maxWidth: 1200, margin: "0 auto" }}>
        <h2 style={{
          textAlign: "center", fontFamily: "'Space Grotesk',sans-serif",
          fontSize: "2rem", fontWeight: 700, marginBottom: "3rem"
        }}>
          Everything you need to <span className="gradient-text">transform your health</span>
        </h2>
        <div style={{
          display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))", gap: "1.5rem"
        }}>
          {[
            { icon: <Brain size={24} />, title: "AI Plan Generation", desc: "AI creates a personalized daily plan tailored to your BMI, TDEE, allergies, and specific health goals.", color: "#8b5cf6" },
            { icon: <Utensils size={24} />, title: "Real Recipe Database", desc: "Plans use 837+ real recipes from a curated database. Every meal suggestion comes with ingredients and nutrition info.", color: "#10b981" },
            { icon: <Shield size={24} />, title: "Allergy Safe", desc: "73 allergy categories tracked. Recipes are filtered to exclude any ingredient that may trigger your allergies.", color: "#f43f5e" },
            { icon: <TrendingUp size={24} />, title: "Progress Tracking", desc: "Track your daily tasks, monitor streaks, and visualize your progress with interactive charts and calendars.", color: "#3b82f6" },
            { icon: <Activity size={24} />, title: "BMI & TDEE Calculator", desc: "Auto-calculated metrics: BMI, BMR, TDEE. Your calorie targets adapt to your body and activity level.", color: "#f59e0b" },
            { icon: <Target size={24} />, title: "Goal-Focused", desc: "Weight loss, muscle gain, endurance, flexibility or maintenance — choose your goal and get a matching plan.", color: "#06b6d4" },
          ].map((f) => (
            <div key={f.title} className="card glass-hover" style={{ cursor: "default" }}>
              <div style={{
                width: 48, height: 48, borderRadius: 12,
                background: `${f.color}22`, border: `1px solid ${f.color}44`,
                display: "flex", alignItems: "center", justifyContent: "center",
                color: f.color, marginBottom: "1rem"
              }}>
                {f.icon}
              </div>
              <h3 style={{ fontWeight: 700, fontSize: "1rem", marginBottom: "0.5rem" }}>{f.title}</h3>
              <p style={{ color: "var(--text-secondary)", fontSize: "0.875rem", lineHeight: 1.6 }}>{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section style={{
        textAlign: "center", padding: "5rem 2rem",
        background: "linear-gradient(180deg, transparent, rgba(59,130,246,0.05))"
      }}>
        <h2 style={{ fontFamily: "'Space Grotesk',sans-serif", fontSize: "2.2rem", fontWeight: 800, marginBottom: "1rem" }}>
          Ready to start your health journey?
        </h2>
        <p style={{ color: "var(--text-secondary)", marginBottom: "2rem" }}>
          Join users who are already transforming their health with AI-powered plans.
        </p>
        <Link href="/register">
          <button className="btn-primary animate-pulse-glow" style={{ padding: "1rem 2.5rem", fontSize: "1.1rem" }}>
            <Zap size={20} /> Create My Free Plan
          </button>
        </Link>
      </section>

      {/* Footer */}
      <footer style={{
        borderTop: "1px solid var(--border)", padding: "1.5rem 2rem",
        textAlign: "center", color: "var(--text-muted)", fontSize: "0.85rem"
      }}>
        © 2025 AI Health Planner · Built with Next.js
      </footer>
    </div>
  );
}
